### ISSUE TITLE
how fix this?

### ISSUE THREAD

**Issue by josecuervo2019** [sindresorhus/p-waterfall#3]
[14:17:02] [Netty Worker IO Thread #6/ERROR]: [host69.190-231-96.telecom.net.ar/190.231.96.69:51986|IICesarKill14II] -> UpstreamBridge - encountered exception
java.lang.IllegalArgumentException: Chat message is empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:138) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by sindresorhus** [comment]
That is totally unrelated to this project...
